# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e182a2c6c48825d4c06ced2f70b566077f490ecd6aebb8a7f56912ac5eedefe36f6f75f4625e499c3469c1b1697b6ae242302c63fdfd272602e3be1a8330376b

test:
  secret_key_base: 14dec2535cd57dbf69e95e54ad0eb218369223e8ff5d0bb4950b7153de87e19504aea715aa5bd88d31acffad394b1944f0b9ce7f506394d6c054316a810dfa86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
